import express from 'express';
import {randomBytes,randomUUID,scryptSync,timingSafeEqual,createHash} from 'node:crypto';
import {readFile} from 'node:fs/promises';
import path from 'node:path';
import {pool} from './storage';
import {userContext,type User} from './auth-context';
import {GET,POST} from './shop';
const app=express();app.set('trust proxy',1);app.disable('x-powered-by');const secure=process.env.COOKIE_SECURE!=='false';
app.use((req,res,next)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','same-origin');res.setHeader('X-Frame-Options','DENY');res.setHeader('Content-Security-Policy',"default-src 'self'; img-src 'self' data: blob:; media-src 'self' blob:; script-src 'self'; style-src 'self' 'unsafe-inline'; connect-src 'self'; frame-ancestors 'none'; base-uri 'self'; form-action 'self'");if(req.path.startsWith('/api/'))res.setHeader('Cache-Control','no-store');next();});
app.get('/health',async(req,res)=>{try{await pool.query('SELECT 1');res.json({ok:true})}catch{res.status(503).json({ok:false})}});
const digest=(s:string)=>createHash('sha256').update(s).digest('hex');
function hash(p:string){const salt=randomBytes(16).toString('hex');return salt+':'+scryptSync(p,salt,64).toString('hex');}
function verify(p:string,stored:string){const [salt,value]=stored.split(':');if(!salt||!value)return false;const a=scryptSync(p,salt,64),b=Buffer.from(value,'hex');return a.length===b.length&&timingSafeEqual(a,b);}
const cookie=(req:express.Request,name:string)=>req.headers.cookie?.split(';').map(x=>x.trim()).find(x=>x.startsWith(name+'='))?.slice(name.length+1)||'';
async function current(req:express.Request):Promise<User|null>{const token=cookie(req,'shop_login');if(!token)return null;const r=await pool.query('SELECT a.*,s.expires FROM accounts a JOIN auth_sessions s ON a.id=s.user_id WHERE s.token_hash=$1 AND s.expires>$2',[digest(token),Date.now()]);const a=r.rows[0];return a?{userId:a.id,email:a.email,displayName:a.email,mustChange:a.must_change}:null;}
async function session(res:express.Response,userId:string){const token=randomBytes(32).toString('hex');await pool.query('DELETE FROM auth_sessions WHERE expires<$1',[Date.now()]);await pool.query('INSERT INTO auth_sessions(token_hash,user_id,expires) VALUES($1,$2,$3)',[digest(token),userId,Date.now()+43200000]);res.cookie('shop_login',token,{httpOnly:true,secure,sameSite:'lax',path:'/',maxAge:43200000});}
const failures=new Map<string,{count:number,until:number}>();
app.use('/api',express.raw({type:()=>true,limit:'10mb'}));
app.use('/api',async(req,res,next)=>{if(req.method!=='GET'){const origin=req.get('Origin');if(!origin||new URL(origin).host!==req.get('Host')){res.status(403).json({error:'Yêu cầu không hợp lệ.'});return;}}next();});
app.get('/api/auth',async(req,res)=>{try{const user=await current(req);const owner=(await pool.query("SELECT value FROM settings WHERE key='owner'")).rows[0];res.json({authenticated:!!user,mustChange:user?.mustChange||false,setupNeeded:!owner});}catch{res.status(503).json({error:'Chưa kết nối được cơ sở dữ liệu.'})}});
app.post('/api/auth',async(req,res)=>{try{const b=JSON.parse(Buffer.from(req.body).toString('utf8'));const ip=req.ip||'unknown',limit=failures.get(ip);if(limit&&limit.until>Date.now()){res.status(429).json({error:'Nhập sai nhiều lần. Thử lại sau 5 phút.'});return;}const fail=()=>{const count=(limit?.count||0)+1;failures.set(ip,{count,until:count>=5?Date.now()+300000:0});};if(typeof b.password!=='string'||b.password.length<8||b.password.length>128){res.status(400).json({error:'Mật khẩu cần từ 8 đến 128 ký tự.'});return;}if(b.action==='setup'){const owner=(await pool.query("SELECT value FROM settings WHERE key='owner'")).rows[0];if(owner){res.status(403).json({error:'Chủ cửa hàng đã được thiết lập.'});return;}const configured=process.env.BOOTSTRAP_TOKEN;if(!configured||typeof b.token!=='string'||!timingSafeEqual(Buffer.from(digest(b.token)),Buffer.from(digest(configured)))){fail();res.status(403).json({error:'Mã thiết lập không đúng.'});return;}if(typeof b.email!=='string'||!/^\S+@\S+\.\S+$/.test(b.email)){res.status(400).json({error:'Email không hợp lệ.'});return;}const client=await pool.connect(),id=randomUUID();try{await client.query('BEGIN');await client.query("SELECT pg_advisory_xact_lock(178334)");if((await client.query("SELECT value FROM settings WHERE key='owner'")).rows.length)throw Error('Cửa hàng đã được thiết lập.');await client.query('INSERT INTO accounts(id,email,password_hash,must_change) VALUES($1,$2,$3,false)',[id,b.email.toLowerCase().trim(),hash(b.password)]);await client.query("INSERT INTO settings(key,value) VALUES('owner',$1)",[id]);await client.query('COMMIT');}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}await session(res,id);failures.delete(ip);res.json({ok:true});return;}
if(b.action==='change'){const user=await current(req);if(!user){res.status(401).json({error:'Vui lòng đăng nhập.'});return;}const row=(await pool.query('SELECT password_hash FROM accounts WHERE id=$1',[user.userId])).rows[0];if(typeof b.oldPassword!=='string'||b.oldPassword.length>128||!verify(b.oldPassword,row.password_hash)){fail();res.status(403).json({error:'Mật khẩu hiện tại không đúng.'});return;}await pool.query('UPDATE accounts SET password_hash=$1,must_change=false WHERE id=$2',[hash(b.password),user.userId]);await pool.query('DELETE FROM auth_sessions WHERE user_id=$1',[user.userId]);await session(res,user.userId);res.json({ok:true});return;}
if(b.action!=='login'){res.status(400).json({error:'Thao tác không hợp lệ.'});return;}const a=(await pool.query('SELECT * FROM accounts WHERE email=$1',[String(b.email||'').toLowerCase().trim()])).rows[0];if(!a||!verify(b.password,a.password_hash)){fail();res.status(403).json({error:'Email hoặc mật khẩu không đúng.'});return;}await session(res,a.id);failures.delete(ip);res.json({ok:true,mustChange:a.must_change});}catch(e){console.error('Authentication failed');res.status(503).json({error:'Không thực hiện được. Hãy thử lại.'})}});
app.get('/logout',async(req,res)=>{try{await pool.query('DELETE FROM auth_sessions WHERE token_hash=$1',[digest(cookie(req,'shop_login'))]);}catch{}res.clearCookie('shop_login',{path:'/',secure,httpOnly:true,sameSite:'lax'});res.clearCookie('shop_stats',{path:'/',secure,httpOnly:true,sameSite:'strict'});res.redirect('/');});
app.all('/api/shop',async(req,res)=>{try{const user=await current(req);if(!user){res.status(401).json({error:'Vui lòng đăng nhập tài khoản cửa hàng.'});return;}if(user.mustChange){res.status(403).json({error:'Cần đổi mật khẩu tạm trước khi sử dụng.'});return;}if(!['GET','POST'].includes(req.method)){res.status(405).end();return;}if(req.method==='POST'&&req.is('application/json')){const b=JSON.parse(Buffer.from(req.body).toString('utf8'));if(b.action==='member'){const owner=(await pool.query("SELECT value FROM settings WHERE key='owner'")).rows[0]?.value;if(owner!==user.userId){res.status(403).json({error:'Chỉ chủ cửa hàng có quyền.'});return;}const email=String(b.email||'').trim().toLowerCase();if(!/^\S+@\S+\.\S+$/.test(email)||email===user.email){res.status(400).json({error:'Email nhân viên không hợp lệ.'});return;}if(b.remove){const client=await pool.connect();try{await client.query('BEGIN');await client.query('DELETE FROM members WHERE email=$1',[email]);await client.query('DELETE FROM auth_sessions WHERE user_id IN(SELECT id FROM accounts WHERE email=$1)',[email]);await client.query('DELETE FROM accounts WHERE email=$1',[email]);await client.query('COMMIT');}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}res.json({ok:true});return;}if((await pool.query('SELECT id FROM accounts WHERE email=$1',[email])).rows.length){res.status(409).json({error:'Tài khoản đã tồn tại.'});return;}const temporaryPassword=randomBytes(12).toString('base64url'),client=await pool.connect();try{await client.query('BEGIN');await client.query('INSERT INTO accounts(id,email,password_hash) VALUES($1,$2,$3)',[randomUUID(),email,hash(temporaryPassword)]);await client.query("INSERT INTO members(email,role) VALUES($1,'staff')",[email]);await client.query('COMMIT');}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}res.json({ok:true,temporaryPassword});return;}}
const headers=new Headers();for(const [k,v] of Object.entries(req.headers))if(v)headers.set(k,Array.isArray(v)?v.join(','):v);headers.set('origin','https://'+req.get('Host'));const request=new Request('https://'+req.get('Host')+req.originalUrl,{method:req.method,headers,body:req.method==='POST'?new Uint8Array(req.body):undefined});const response=await userContext.run(user,()=>req.method==='GET'?GET(request):POST(request));res.status(response.status);response.headers.forEach((v,k)=>res.setHeader(k,v));res.send(Buffer.from(await response.arrayBuffer()));}catch{res.status(503).json({error:'Không thực hiện được. Hãy thử lại.'})}});
app.use(express.static(path.resolve('dist'),{index:false}));app.get('/',(req,res)=>res.sendFile(path.resolve('dist/index.html')));app.use((req,res)=>res.status(404).json({error:'Không tìm thấy trang.'}));app.use((err:any,req:express.Request,res:express.Response,next:express.NextFunction)=>res.status(err.type==='entity.too.large'?413:500).json({error:err.type==='entity.too.large'?'Ảnh quá lớn. Tối đa 8 MB.':'Không thực hiện được yêu cầu.'}));
if(!process.env.DATABASE_URL||!process.env.BOOTSTRAP_TOKEN)throw Error('DATABASE_URL and BOOTSTRAP_TOKEN are required');await pool.query(await readFile(new URL('./schema.sql',import.meta.url),'utf8'));app.listen(Number(process.env.PORT||3000),'0.0.0.0',()=>console.log('Laundry service ready'));
