import {useState} from 'react';
type Photo={id:string,label?:string};
type Props={photos:Photo[],checked:string[],onChange:(ids:string[])=>void,onSave:()=>void,onComplete:()=>void,busy:boolean,customer:string};
export default function Checkout({photos,checked,onChange,onSave,onComplete,busy,customer}:Props){
  const [index,setIndex]=useState(0),[showMissing,setShowMissing]=useState(false),[loaded,setLoaded]=useState('');
  const current=photos[index],confirmed=new Set(checked),missing=photos.filter(p=>!confirmed.has(p.id));
  function move(i:number){setIndex((i+photos.length)%photos.length);}
  function toggle(){if(!current)return;const next=confirmed.has(current.id)?checked.filter(id=>id!==current.id):[...checked,current.id];onChange(next);}
  function finish(){if(missing.length||!photos.length){setShowMissing(true);onSave();return;}onComplete();}
  return <section className="checkout-review"><h2>Kiểm tra đồ của {customer}</h2><p className="muted">Lướt ảnh để tìm món đang cầm. Chỉ đánh dấu khi đã tìm đủ đồ trong ảnh; ảnh chụp nhóm cần kiểm đủ cả nhóm.</p><div className="review-progress"><strong>Đã kiểm {photos.length-missing.length}/{photos.length} ảnh</strong><span className={missing.length?'late':'ok'}>{photos.length?(missing.length?`Còn ${missing.length} ảnh chưa xác nhận`:'Đã đối chiếu đủ tất cả ảnh'):'Chưa có ảnh check-in'}</span></div>{current?<><div className={'review-photo '+(confirmed.has(current.id)?'confirmed':'')}><img key={current.id} src={'/api/shop?action=photo&id='+current.id} alt={current.label||`Ảnh check-in ${index+1}`} onLoad={()=>setLoaded(current.id)} onError={()=>setLoaded('')}/><span className="review-number">Ảnh {index+1}/{photos.length}</span>{confirmed.has(current.id)&&<span className="review-confirmed">✓ Đã tìm đủ</span>}</div><h3>{current.label||`Ảnh check-in ${index+1}`}</h3><div className="actions review-controls"><button disabled={busy||photos.length<2} onClick={()=>move(index-1)}>← Ảnh trước</button><button className={confirmed.has(current.id)?'checked-button':'primary'} aria-pressed={confirmed.has(current.id)} disabled={busy||(!confirmed.has(current.id)&&loaded!==current.id)} onClick={toggle}>{confirmed.has(current.id)?'✓ Đã có · Bỏ đánh dấu':'✓ Có đủ đồ trong ảnh'}</button><button disabled={busy||photos.length<2} onClick={()=>move(index+1)}>Ảnh tiếp →</button></div><div className="review-thumbs" aria-label="Chọn ảnh check-in">{photos.map((p,i)=><button key={p.id} className={i===index?'selected':''} aria-label={`Ảnh ${i+1}${confirmed.has(p.id)?', đã có':', chưa xác nhận'}`} aria-current={i===index?'true':undefined} disabled={busy} onClick={()=>move(i)}><img src={'/api/shop?action=photo&id='+p.id} alt=""/><span>{i+1}{confirmed.has(p.id)?' ✓':''}</span></button>)}</div></>:<div className="empty">Đơn này chưa có ảnh check-in. Không thể xác nhận đủ đồ bằng ảnh.</div>}{showMissing&&missing.length>0&&<div className="missing-panel" role="alert"><h3>Chưa hoàn tất: còn {missing.length} ảnh chưa xác nhận đủ đồ</h3><p>Bấm vào ảnh dưới đây để quay lại kiểm tra. Đơn vẫn ở trạng thái đang giặt.</p><div className="photos">{missing.map(p=><button key={p.id} disabled={busy} onClick={()=>move(photos.indexOf(p))}><img src={'/api/shop?action=photo&id='+p.id} alt={p.label||'Ảnh chưa xác nhận'}/><span>{p.label||`Ảnh check-in ${photos.indexOf(p)+1}`}</span></button>)}</div></div>}<div className="actions review-finish"><button disabled={busy} onClick={onSave}>{busy?'Đang lưu…':'Lưu tiến độ kiểm tra'}</button><button className="primary" disabled={busy||!photos.length} onClick={finish}>Hoàn tất check-out</button></div><p className="muted">Chỉ chuyển sang chờ bàn giao khi tất cả ảnh check-in đã được xác nhận. Bấm lưu tiến độ trước khi rời đơn.</p></section>;
}
